Debug "1"

GenericPunctNone ""
GenericPunctSome "--punct=\"()[]{};:\""
GenericPunctMost "--punct=\"()[]{};:\""
GenericPunctAll "--punct"

GenericRateAdd 1
GenericPitchAdd 1
GenericVolumeAdd 1
GenericRateMultiply 1
GenericPitchMultiply 750

GenericExecuteSynth "printf %s '$DATA' \
| piper-tts --model '/usr/share/piper-voices/$VOICE.onnx' --output_raw \
| sox -v 0.8 -r $(jq .audio.sample_rate < '/usr/share/piper-voices/'$VOICE'.onnx.json') -c 1 \
  -b 16 -e signed-integer -t raw - -t wav - tempo $RATE pitch $PITCH norm \
| $PLAY_COMMAND"

GenericCmdDependency "piper-tts"
GenericCmdDependency "jq"
GenericCmdDependency "sox"

AddVoice "en-US" "MALE1" "en/en_US/ryan/low/en_US-ryan-low"
AddVoice "en-US" "MALE1" "en/en_US/ryan/high/en_US-ryan-high"
AddVoice "en-US" "MALE1" "en/en_US/ryan/medium/en_US-ryan-medium"
AddVoice "en-US" "MALE1" "en/en_US/norman/medium/en_US-norman-medium"
AddVoice "en-US" "FEMALE1" "en/en_US/amy/low/en_US-amy-low"
AddVoice "en-US" "FEMALE1" "en/en_US/amy/medium/en_US-amy-medium"
AddVoice "en-US" "MALE1" "en/en_US/lessac/low/en_US-lessac-low"
AddVoice "en-US" "MALE1" "en/en_US/lessac/high/en_US-lessac-high"
AddVoice "en-US" "MALE1" "en/en_US/lessac/medium/en_US-lessac-medium"
AddVoice "en-US" "MALE1" "en/en_US/joe/medium/en_US-joe-medium"
AddVoice "en-US" "MALE2" "en/en_US/kathleen/low/en_US-kathleen-low"
AddVoice "en-US" "CHILD_MALE" "en/en_US/kristin/medium/en_US-kristin-medium"
AddVoice "en-US" "MALE1" "en/en_US/hfc_male/medium/en_US-hfc_male-medium"
AddVoice "en-US" "MALE1" "en/en_US/arctic/medium/en_US-arctic-medium"
AddVoice "en-US" "FEMALE1" "en/en_US/hfc_female/medium/en_US-hfc_female-medium"
AddVoice "en-US" "FEMALE1" "en/en_US/libritts/high/en_US-libritts-high"
AddVoice "en-US" "MALE1" "en/en_US/danny/low/en_US-danny-low"
AddVoice "en-US" "MALE1" "en/en_US/bryce/medium/en_US-bryce-medium"
AddVoice "en-US" "MALE1" "en/en_US/l2arctic/medium/en_US-l2arctic-medium"
AddVoice "en-US" "FEMALE1" "en/en_US/ljspeech/high/en_US-ljspeech-high"
AddVoice "en-US" "FEMALE1" "en/en_US/ljspeech/medium/en_US-ljspeech-medium"
AddVoice "en-US" "FEMALE1" "en/en_US/libritts_r/medium/en_US-libritts_r-medium"
AddVoice "en-US" "MALE1" "en/en_US/kusal/medium/en_US-kusal-medium"
AddVoice "en-US" "MALE1" "en/en_US/john/medium/en_US-john-medium"

AddVoice "en-GB" "FEMALE1" "en/en_GB/alan/low/en_GB-alan-low"
AddVoice "en-GB" "FEMALE1" "en/en_GB/alan/medium/en_GB-alan-medium"
AddVoice "en-GB" "FEMALE1" "en/en_GB/cori/high/en_GB-cori-high"
AddVoice "en-GB" "FEMALE1" "en/en_GB/cori/medium/en_GB-cori-medium"
AddVoice "en-GB" "FEMALE1" "en/en_GB/jenny_dioco/medium/en_GB-jenny_dioco-medium"
AddVoice "en-GB" "FEMALE1" "en/en_GB/aru/medium/en_GB-aru-medium"
AddVoice "en-GB" "MALE1" "en/en_GB/northern_english_male/medium/en_GB-northern_english_male-medium"
AddVoice "en-GB" "FEMALE1" "en/en_GB/vctk/medium/en_GB-vctk-medium"
AddVoice "en-GB" "FEMALE1" "en/en_GB/southern_english_female/low/en_GB-southern_english_female-low"
AddVoice "en-GB" "MALE1" "en/en_GB/semaine/medium/en_GB-semaine-medium"
AddVoice "en-GB" "MALE1" "en/en_GB/alba/medium/en_GB-alba-medium"

DefaultVoice             "en/en_US/ryan/high/en_US-ryan-high"

