"Boot with standard options"  "root=UUID=3600cee8-934d-4747-bdfd-017f2ce67551 rw quiet splash apparmor=1 security=apparmor udev.log_priority=3"
"Boot to single-user mode"    "root=UUID=3600cee8-934d-4747-bdfd-017f2ce67551 rw quiet splash apparmor=1 security=apparmor udev.log_priority=3 single"
"Boot with minimal options"   "ro root=/dev/nvme0n1p7"
