"Boot with standard options"  "root=UUID= rw quiet splash apparmor=1 security=apparmor udev.log_priority=3 initrd=boot\intel-ucode.img initrd=boot\initramfs-%v-x86_64.img"
"Boot with fallback initrdamfs"  "root=UUID= rw quiet splash apparmor=1 security=apparmor udev.log_priority=3 initrd=boot\initramfs-%v-x86_64-fallback.img"
"Boot into recovery mode"  "root=UUID= rw initrd=boot\initramfs-%v-x86_64-fallback.img single"
