# "Boot with standard options"  "root=UUID= rw quiet splash apparmor=1 security=apparmor udev.log_priority=3"
# "Boot to single-user mode"    "root=UUID= rw quiet splash apparmor=1 security=apparmor udev.log_priority=3 single"
# "Boot with minimal options"   "ro root="

"Boot with standard options"  "root=UUID= rw quiet splash apparmor=1 security=apparmor udev.log_priority=3 initrd=boot/intel-ucode.img initrd=boot/initramfs-%v.img"
# "Boot to single-user mode"  "root=UUID= rw quiet splash apparmor=1 security=apparmor udev.log_priority=3 initrd=boot/intel-ucode.img initrd=boot/initramfs-%v.img single"
# "Boot with minimal options"   "ro root= initrd=boot/intel-ucode.img initrd=boot/initramfs-%v.img"

# "Boot with standard options [fallback]"  "root=UUID= rw quiet splash apparmor=1 security=apparmor udev.log_priority=3 initrd=boot/initramfs-%v-fallback.img"
# "Boot to single-user mode [fallback]"  "root=UUID= rw quiet splash apparmor=1 security=apparmor udev.log_priority=3 initrd=boot/initramfs-%v-fallback.img single"
"Boot with minimal options [fallback]"   "ro root= initrd=boot/initramfs-%v-fallback.img"
