[options]
BatchInstall
CleanAfter
CombinedUpgrade
Devel
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil -latest
# NewsOnUpgrade
PgpFetch
Provides = all
RemoveMake
SaveChanges
SkipReview
SudoLoop
# UpgradeMenu
UseAsk

[bin]
FileManager = yazi
Pager = bat -p
