wireplumber.profiles = {
  main = {
    monitor.v4l2 = disabled
    -- monitor.libcamera.rules = [
    --   {
    --     actions = {
    --       update-props = {
    --         default.video.width = 1280
    --         default.video.height = 720
    --       }
    --     }
    --   }
    -- ]
  }
}
