#!/bin/bash

sed -e '/DiscoverableTimeout/s/^#[[:space:]]*//' \
  -e '/DiscoverableTimeout = /s/= .*/= 600/' \
  -e '/PairableTimeout/s/^#[[:space:]]*//' \
  -e '/PairableTimeout = /s/= .*/= 600/' \
  -e '/NameResolving/s/^#[[:space:]]*//' \
  -e '/NameResolving = /s/= .*/= true/' \
  -e '/ControllerMode/s/^#[[:space:]]*//' \
  -e '/ControllerMode = /s/= .*/= dual/' \
  -e '/MultiProfile/s/^#[[:space:]]*//' \
  -e '/MultiProfile = /s/= .*/= multiple/' \
  -e '/FastConnectable/s/^#[[:space:]]*//' \
  -e '/FastConnectable = /s/= .*/= true/' \
  -e '/Experimental/s/^#[[:space:]]*//' \
  -e '/Experimental = /s/= .*/= true/' 
