# hybrid.colors
# Color scheme from https://github.com/Mayccoll/Gogh
color0=#000000
color1=#CD0000
color2=#00CD00
color3=#CDCD00
color4=#6495ED
color5=#CD00CD
color6=#00CDCD
color7=#E5E5E5

color8=#7F7F7F
color9=#FF0000
color10=#00FF00
color11=#FFFF00
color12=#5C5CFF
color13=#FF00FF
color14=#00FFFF
color15=#FFFFFF

background=#141414
foreground=#000000
cursor=#DDDDDD
