--enable-features=MiddleClickAutoscroll,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE,VaapiVideoEncoder,VaapiVideoDecoder,WebRtcPipeWireCamera,CameraMicPreview,FluentOverlayScrollbar,OneTimePermission,ParallelDownloading
--ozone-platform-hint=auto
--gtk-version=4
