--enable-features=TouchpadOverscrollHistoryNavigation,MiddleClickAutoscroll,VulkanFromANGLE,VaapiVideoEncoder,VaapiVideoDecoder,WebRtcPipeWireCamera,CameraMicPreview,EnableTabMuting,FluentOverlayScrollbar,FluentScrollbar,ImprovedSigninUIOnDesktop,LinkPreview:trigger_type/alt_click,OneTimePermission,ParallelDownloading,ScrollableTabStrip:minTabWidth/140,kScrollableTabStripOverflow:tabScrollOverflow/2,TabOrganizationSettingsVisibility
--ozone-platform-hint=auto
--gtk-version=4
--process-per-site
