#!/bin/bash

sed -e '/Color/s/^#[[:space:]]*//' \
  -e '/VerbosePkgLists/s/^#[[:space:]]*//' \
  -e '/ILoveCandy/s/^/# /' \
  -e '/CheckSpace/s/^#[[:space:]]*//' \
  -e '/ParallelDownloads/s/^#[[:space:]]*//' \
  -e '/ParallelDownloads = /s/= .*/= 8/'